### PR TITLE
Do not add appendUser and filterOwner middlewares when not using authentication

### LINKED ISSUE #7: TypeError if the Model belongs to User and without authentication
### How to reproduce
1. Add a new route
```bash
# with the api command:
$ flug api

Welcome to the Flugzeug API generator

? Model name: Test
? Would you like your model to belong to User? Yes
? Controller name: Test
? API Version: v1
? Needs authentication? No
   create app/models/Test.ts
   create app/controllers/v1/Test.ts


# or with the controller command:
$ flug controller

Welcome to the Flugzeug Controller generator

? Controller name: Test
? Model: Test
? API Version: v1
? Needs authentication? No
? Does the model belongs to User? Yes
   create app/controllers/v1/Test.ts
```
2. then call it
```bash
curl --location --request GET 'http://localhost:8888/api/v1/test' \
--header 'Accept: application/json'
```
### Result
```
TypeError: Cannot read property 'id' of undefined
    at flug/app/policies/General.ts:56:32
```

### Problem

The `req.session` object is initialized in the `Controller` class, so it is available for all the next middleware. `filterOwner`, `appendUser`, `filterRoles` and `isSelfUser` middlewares use it to retrieve information about the user (from the JWT). But the `req.session.jwt` object is populated only when the `validateJWT` middleware is used when defining the route, which is not the case when the user chooses not to use authentication during the setup.

### PR DESCRIPTION
**Pull request by guham**
This PR closes #7

### CODE REVIEW

File: generators/app/templates/app/libraries/ModelController.ts [hunk 1]
```diff
@@ -90,7 +90,6 @@ export function parseWhere(req: Request): any {
   }
 
   // Merge with req.session.where (Useful for enforcing policies)
-  if (req.session == null) req.session = {};
```
Comment (Rodmg) [inline generators/app/templates/app/libraries/ModelController.ts:93]: @guham What's the reason to remove this?

Comment (guham) [reply generators/app/templates/app/libraries/ModelController.ts:93]: The `ModelController` class extends `Controller`. In the parent constructor, the session object is initialized if it doesn't exist, so this check can be safely removed because the session object always exists.

**Comment by Rodmg** [comment]
Thanks @guham!
